# ~/notes/raggo.org

* RAGGO: a minimal /lingua franca/ of the legendary future

* vowels

** a e i o u

* consonants

** p b t d k g m n ŋ l r w y h s z

* potential lexicon

** ha have
** me tu el vuz  

Raggo Pronouns
|----+-----+-----------+-------|
| me | nos | i/me      | we/us |
| tu | vuz | thou      | ye    |
| el | liz | he/she/it | they  |
|----+-----+-----------+-------|

Verb Paradigm
|--------+-------------------------+----------------------------|
| iza    | is, to be               | present tense              |
| pa iza | was, were               | past tense                 |
| fu iza | will be                 | future tense               |
| izad   | been                    | past participle            |
| izado  | a has been              | past participial nominal   |
| izand  | being                   | active participle          |
| izando | a being                 | active participial nominal |
| la iza | the act of being, to be | verbal noun                |
| iza    | to be                   | infinitive                 |
|--------+-------------------------+----------------------------|

ia: already


ha :: verb :: have
ita:: verb :: go
iza :: verb :: is, to be
hado. itado. izado. 
-i adjective ending. -o noun ending. izado:: noun :: one who is "gone"; a has been

Me ha itad tat asfalto proto horoi forizadi
1s-pronoun have already gone that road for hour.pl gone and many

ta: conditional
ve: optative and imperative
ve ita!! go!!
ve el ita: May he go

Kako geba klizid monon Tamoto
Kak.nom give church.dat money.acc Tamo.oblique
nom=-o, dat=-d, acc=-n, oblique=-to
Kako gives money to the church, relative to Tamo.
I.e., Kako gives more money to the Church than Tamo.
- emphasis is on Kako's giving, with Tamo quite peripheral here.

  
Caco dona monon circoti Tamobo
-o: nom, -ti: dat, -n: acc, -bo: oblique

Caco ultradona Tamon monobo circoti
ultra=OUT -o=nom -n=acc -bo=oblique -ti=dat unda=UNDER
Caco outgives Tamo, concerning money, to the church
- ultra promotes the object of comparison to the Accusative.
- emphasis on the comparison of Caco to Tamo
Caco undadona Tamon monobo circoti
Caco undergives Tamo, concerning money, to the church
- emphasis again on the comparison of Tamo to Caco

for- 
Caco fordona Circon monobo Tamobo
Caco DAT.give church.acc money.Oblique 
-emphasis is on the Recipient


Use /baro/-verb (/giro/-verb? to the valencies such that the Object becomes the subject and the Subject (Agentive or Nominative).
OR
Freely use adjectives as verbs in an "ergative" sense, meaning the logical Object becomes the subject of the sentence, leaving the Agent unspecified (there must be an Agent, unspecified but nonetheless an Agent among the valencies inherent in the meaning of the verb; a door does not open itself, and yet doors open all the time). Assume your lucubrators are at least as intelligent as yourself, but first assume that your are not clever; having killed your darlings, go to town. Gallivant.

ita :: verb :: go
itad :: past participle = verb + d :: itad
itadi :: past participial adjective :: gone
itado :: noun :: a gone one
asfalto road
proto for during
horo hour
horoi hours
forizadi -i :: when an adjective is really just an adjective meaning when its noun is there it becomes undeclinable and ends in -i   
ed :: and
na: and

* Lexicon


for- completely finished probably to destruction

polio many singular
polioi plural
polii many plural

stick to one thousand elements

| present | past participle | imperfect | perfect | pluperfect |''[| iza     | izad            | izaba     | ha izad | had izad   |
| ha      | had             | haba      | ha had  | haba had   |

omo: man or human; pl omoi
Raggo

* Raggo
- Learn Raggo.
- High Raggo for talking to inflated egos.
- Low Raggo for buying drugs and negotiating with prostitutes.
- Speak Midlin. It's mid. (Standard Raggo is called Midlin.)
- The middle of the road no risks language.
** Phonology
*** Learn the alphabet.
a b c d e f g h i j k l m n o p r s t u v w x y z ŋ
