* the first nulin
** the ways words sound
Allaman
momas

limar
alma
almon
oinas
ainas
aonas
lololma
d b g more common than t p k
ʌlloma
dʌl
aönas
ollʌmʌ

** phonology: 
a e i o u
  ai oi ao
b d g
p t k
m n ɲ ŋ
s z
h
l r
v
j c /dʒ tʃ/
w y
ɬ tɬ



** phonotaxis
- permitted initial consonants
  - any consonant may begin a word or syllable
- permitted medial consonants
  - any single consonant is allowed as medial
- permitted medial consonant clusters; all clusters occur only medially
  - lb ld lj lg lp lt lc lk lm ln lɲ lŋ
  - rb rd rj rg rp rt rc rk rm rn rɲ rŋ
  - mb nd ɲj ŋg mp nt ɲc ŋk  
- permitted final consonants
  - m n ɲ ŋ l r ʃ ʒ
- vowel rule
  - any vowel or diphthong may occur singly anywhere
  - a diaresis is added to a vowel if it can be confused with the
  - glide of a diphthong ai = diphthong; aï = two syllables
  - No vowel can occur immediately after ʌ. but ʌ can follow a vowel
    
permitted geminations
bb dd jj gg pp tt cc kk :: jj /ddʒ/, cc /ttʃ/
mm nn ɲɲ ŋŋ
ll rr

gemination is always the result of grammatical processes acting on
roots; no root starts out with a gemminated consonant.

permitted word shapes
note: K = cluster
- V CV VC CVC VKV CVKV VKVC CVKVC VCVCV CVCVCV VCVCVC VKVCV CVKVCV
CVKVCVC VCVKV VCVKVC CVCVKV CVCVKVC










* the second nulin

 probably not :: em :: particle :: predicate marker
probably not :: eham :: pronoun :: 1st person singular; 1/me/mine

- consonants
  
b d
  t k
m n g
v
  s,z
     sh,zh
w   y
  l r

h

- vowels
  a e i o u ì

- wesh :: female specimen of; she-; a female; a woman
  - wewesh :: wesh, plural

    -alam :: verbal root :: to go
    |---------+-----------------------+---------|
    |         | singular              | plural  |
    |---------+-----------------------+---------|
    | 1st     | nalam                 | nenalam |
    | 2nd     | salam                 | sesalam |
    | 3rd     | talam                 | tetalam |
    |---------+-----------------------+---------|
    | unspec. | halam                 |         |
    | null    | lalam                 |         |
    | recip.  | "to go" has no recip  |         |
    | reflex. | "to go" has no reflex |         |
    |---------+-----------------------+---------|
    

talam Eskaram tos totai.
gorgoma vepri :: 

-ai :: time
-au :: place
-oi :: manner-method-means
-ei :: reason
-or :: person
-epri :: 
-ʌmno :: 
-iä ::
talam

aonos sekai :: 
seŋka ::

The monuments of the Dead Gods tower and brood in the wilds of the
world.  The Dead Gods are gone but their ghosts still haunt their
lesser, incarnate and all-too-human siblings.  Their bones power the
dark magic of witches and sorcerers.  Cults worshipping their ghosts
maintain the walls of cities, which would delapidate without the daily
sacrifices.  With no sweet savor of burned flesh ascending to the
clouds no rain would fall.  Everywhere men and women suffer because of
the greed and hunger of the Dead Gods and their greatest devotees: the
kings of the new city states.  For the world is young, iron is known
only from meteoric chunks found in deserts, mammoths yet roam the
steppes, and lions are a universal lurking fear in the trackless wilds
-- and the wilds are everywhere, in every direction, to the ends of
the world.  Even from a vantage atop the mudbrick outer walls of the
cities, where the murengers stand their posts with copper-tipped
spears flashing in moonlight, in firelight, the howling of wolves can,
on some cold nights, be heard in the distance.

To be human in these days is to be a slave.  Even Kings are slaves to
the Dead Gods.  The priests constantly say so, so it must be true,
Malaman thought.  This thought of his was not sincere; it was a future
quip, or snipe, that he would share with one of his fellow murengers
some night.  He'd tell it to Blah or to Yadda and the other man would
laugh and so the night would pass.  That was life.  Each morning he
would return to the tenement where he slept but otherwise spent little
time.  He would sleep, rise some hours before sunset, then go out to
the market.  Spending a few hours in the public life of the men of the
city, he would forget the Pale, which was his charge when he was at
his post.  For upon the Wall, or Pale, all their lives depended.

