# ~/notes/raggo.org

* RAGGO: a minimal /lingua franca/ of the legendary future

* vowels

** a e i o u

* consonants

** p b t d k g m n ŋ l r w y h s z

* potential lexicon

** ha have
** me tu el vuz  
veken 


need words: war peace quiet loud

yâhor :: war
kûlûrr
heretom 
kush 

Raggo
|----+-----+-----------+-------|
| me | nos | i/me      | we/us |
| tu | vuz | thou      | ye    |
| el | liz | he/she/it | they  |
|----+-----+-----------+-------|



ha :: verb :: have
ita:: verb :: go
iza :: verb :: is, to be
hado. itado. izado. 
-i adjective ending. -o noun ending. izado:: noun :: one who is "gone"; a has been

Me ha jed itad tat asfalto proto horoi forizadi polli

Use /baro/-verb (/giro/-verb? to the valencies such that the Object becomes the subject and the Subject (Agentive or Nominative).
OR
Freely use adjectives as verbs in an "ergative" sense, meaning the logical Object becomes the subject of the sentence, leaving the Agent unspecified (there must be an Agent, unspecified but nonetheless an Agent among the valencies inherent in the meaning of the verb; a door does not open itself, and yet doors open all the time). Assume your lucubrators are at least as intelligent as yourself, but first assume that your are not clever; having killed your darlings, go to town. Gallivant.

1s-pronoun have already gone that road for hour.pl gone and many
ita :: verb :: go
itad :: past participle = verb + d :: itad
itadi :: past participial adjective :: gone
itado :: noun :: a gone one
asfalto road
proto for during
horo hour
horoi hours
forizadi -i :: when an adjective is really just an adjective meaning when its noun is there it becomes undeclinable and ends in -i   
ed :: and


for- completely finished probably to destruction

polio many singular
polioi plural
polii many plural

stick to one thousand elements

| present | past participle | imperfect | perfect | pluperfect |
| iza     | izad            | izaba     | ha izad | had izad   |
| ha      | had             | haba      | ha had  | haba had   |

omo: man or human; pl omoi
